fix CI error in print_metrics_regression(**results_dict[name])
TypeError: print_metrics_regression() missing 2 required positional arguments: 'targets' and 'preds'